angelapp/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views
app_name = 'angelapp'

urlpatterns = [
    path(r'', views.List_user_page.as_view(), name='home'),
    path(r'<int:pk>', views.detailView.as_view(), name='detail'),
    path(r'send/<str:reg_id>/<str:firebase_id>/', views.send_notifications, name='send'),
    path(r'createquote/',views.create_quote,name="create_quote"),
    path(r'quotes/', views.List_quotes.as_view(), name='quote'),
    path(r'updateSeeker/',views.update_seekers,name="updateSeeker"),
    path(r'terms/',views.terms.as_view(),name="terms")
  
]

angelproject/urls.py
from django.contrib import admin
#<<<<<<< HEAD
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('angelapp/',include('angelapp.urls'))
    
# #=======
# #from angelapp import views
# from django.urls import path, include,re_path

# #urlpatterns = [
# #    path('admin/', admin.site.urls),
# #    re_path(r'^$',views.HomePage.as_view(),name='homepage'),
# #    re_path(r'^angelapp/',include("angelapp.urls")),
# #    path('accounts/', include('django.contrib.auth.urls'))
# #>>>>>>> e671e54a0bbc2726c7dec09c91f37eea12271ccb
]


# Username (leave blank to use 'kentheangel'): angel
# Email address: kendarules@gmail.com
# Password: Kaneki3kenda

angelapp/models.py
from django.db import models
from django.core.validators import URLValidator

# Create your models here.


class angeltable(models.Model):
    confirmPassword = models.TextField(max_length=100, null=True, blank=True)
    created_Date = models.TextField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=10000, null=True, blank=True)
    deviceToken = models.TextField(max_length=1000, null=True, blank=True)
    email = models.EmailField(
        max_length=70, null=True, blank=True, unique=True)
    firstname = models.TextField(max_length=100, null=True, blank=True)
    gender = models.TextField(max_length=100, null=True, blank=True)
    firebase_id = models.TextField(max_length=500, null=True, blank=True)
    lastName = models.TextField(max_length=100, null=True, blank=True)
    password = models.TextField(max_length=100, null=True, blank=True)
    profilePic = models.TextField(models.TextField(
        validators=[URLValidator()]), null=True, blank=True)
    username = models.TextField(max_length=100, null=True, blank=True)
    flag = models.BooleanField(default=False)


class theripsttable(models.Model):
    created_Date = models.DateTimeField(null=True, blank=True)
    description = models.TextField(max_length=10000, null=True, blank=True)
    deviceToken = models.TextField(max_length=1000, null=True, blank=True)
    email = models.EmailField(
        max_length=70, null=True, blank=True, unique=True)
    firstname = models.TextField(max_length=100, null=True, blank=True)
    gender = models.TextField(max_length=100, null=True, blank=True)
    firebase_id = models.TextField(max_length=500, null=True, blank=True)
    lastName = models.TextField(max_length=100, null=True, blank=True)
    profession = models.TextField(max_length=10000, null=True, blank=True)
    profilePic = models.TextField(models.TextField(
        validators=[URLValidator()]), null=True, blank=True)
    userId = models.TextField(max_length=1000, null=True, blank=True)
    username = models.TextField(max_length=100, null=True, blank=True)


class question_set(models.Model):
    questions = models.TextField(max_length=500, null=True, blank=True)
    firebase_id = models.TextField(max_length=500, null=True, blank=True)
    answers = models.TextField(max_length=100, null=True, blank=True)

class quotes(models.Model):
    firebase_id = models.TextField(max_length=500, null=True, blank=True)
    quotes = models.TextField(max_length=500, null=True, blank=True)



class fcm_info(models.Model):
    fcm_token = models.CharField(max_length=400)

    def __str__(self):
    	return self.fcm_token

angelapp/forms.py
from django import forms

from .models import quotes

class PostForm(forms.ModelForm):

    class Meta:
        model = quotes
        exclude = ('firebase_id',)

angelapp/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
import pyrebase 
from django.http import HttpResponse, HttpResponseRedirect
from .models import fcm_info, angeltable, quotes
from .forms import PostForm
from pyfcm import FCMNotification
from firebase_to_db import update_db

# Create your views here.

config = {
    "apiKey": "AIzaSyCUJgLF1b8HoRouY40zzb4HxL13tQGjlSo",
    "authDomain": "angel-5ac50.firebaseapp.com",
    "databaseURL": "https://angel-5ac50.firebaseio.com",
    "projectId": "angel-5ac50",
    "storageBucket": "angel-5ac50.appspot.com",
    "messagingSenderId": "783783522765"
}
firebase = pyrebase.initialize_app(config)
db = firebase.database()

class IndexView(TemplateView):
    template_name = 'base.html'
    #free_user = dict(db.child("FREE_USER").get().val())
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASE INJECTION!'
        return context


class List_user_page(ListView):
    model = angeltable
    template_name = 'angelapp/list_seekers_page.html'

class List_quotes(ListView):
    model = quotes
    template_name = 'angelapp/quotes.html'


def create_quote(request):
    if request.method == 'POST' :
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            quote = form.cleaned_data['quote']
            data = {"quote": quote}               
            db.child("quotes").push(data)
            form.cleaned_data['firebase_id'] = list(dict(db.child("quotes").get().val()).keys())[-1]
            send_quotes(quote)
            form.save(commit=True)
            return HttpResponseRedirect('/')
    else:
        form = PostForm()

    return render(request, 'angelapp/create_quotes.html', {'form': form})

class detailView(DetailView):
    context_object_name = 'details'
    model = angeltable
    template_name = 'angelapp/seekers_details.html'

def send_notifications(request, reg_id,firebase_id):
    print(reg_id,firebase_id)
    db.child("FREE_USER").child(firebase_id).update({"flag": 1})
    path_to_fcm = "https://fcm.googleapis.com"
    server_key = 'AAAAtn0jcc0:APA91bEI5Ur4NoRS4LroaxFCkQ_RUit5kXSerhmtG_iDdgq9u4EKhfnsP5aayuBiK86qdr7G76BHGk4Vjduf5CDQjm9vabyIh-yUzllYBNcltUfi4wWKz4xxguRkIe1N33uF-YXf9QDE'
    message_title = "Chat Enabled"
    message_body = "Hello Friend:), Now you can ask your queries with one of our executives!"
    print(reg_id)
    result = FCMNotification(api_key=server_key).notify_single_device(
        registration_id=reg_id, message_title=message_title, message_body=message_body)
    return HttpResponse(result)

class terms(TemplateView):
    template_name = 'termsandconditions.html'

# def send_quotes(quote):
#     path_to_fcm = "https://fcm.googleapis.com"
#     server_key = 'AIzaSyA9l1_zDczB2Z1JkfmupsZ6gMljHhVKmnE'
#     list(dict(db.child("FREE_USER").get().val()).keys())
#     reg_id = [k["deviceToken"] for v, k in db.child("FREE_USER").get().val().items() if type(k) == dict]
#     message_title = "Quote of the day"
#     message_body = quote
#     print(reg_id)
#     result = FCMNotification(api_key=server_key).notify_single_device(
#         registration_id=reg_id, message_title=message_title, message_body=message_body)
#     return 

def update_seekers(request):
    update_db()
    return HttpResponseRedirect('/angelapp/')

templates/angelapp/base.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load staticfiles %}
{% comment %} {% if user.is_authenticated %} {% endcomment %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Angel Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Cinzel|Courgette|Noticia+Text" rel="stylesheet">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href=" {{ STATIC_URL }}style.css ">
  </head>
  <body>
  <nav class="navbar navbar-dark bg-dark navbar-expand-lg"><strong>
  <a class="navbar-brand" href="#" style="display=inline-block;text-overflow;color:#FFFFFF;">Angelproject</a>
</strong>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
     <a class="nav-item nav-link active" href="{% url 'angelapp:home'%}">Users <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'angelapp:quote' %}">Quotes</a>
      <a class="nav-item nav-link" href="{% url 'angelapp:create_quote'%}">Create Quote</a>
      <a class="nav-item nav-link" href="#">Update</a>
    </ul>
  </div>
</nav>
<div class="container" >
{% block body_block %}
{% endblock %}
</div>
  </div>
</div>

</div>
  <!--Footer-->
<footer class="page-footer font-small blue pt-4 mt-4">

    <!--Footer Links-->

    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        <div class="container-fluid">


        </div>
    </div>
    <!--/.Copyright-->

</footer>
  </body>
</html>
{% comment %} {% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %} {% endcomment %}

templates/angelapp/basic.html
<!DOCTYPE html>
  <html>
    <head><meta charset="utf-8">
      <title>Angel Project</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css?family=Cinzel|Courgette|Noticia+Text" rel="stylesheet">
      <link rel="stylesheet" src="">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.7/css/mdb.min.css" />
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
      <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <strong>
        <a class="navbar-brand" href="#" style="display:inline-block;text-overflow;color:#FFFFFF;">Angelproject</a>
      </strong>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'opform' %}">Home<span class="sr-only">(current)</span></a>
      </li> -->
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'dashboard' %}" > <strong>Sign in Angel</strong></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url '' %}" ><strong>Sign in Free spirit</strong></a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{% url '' %}"><strong>About us</strong></a>
        </li>
    </ul>
  </div>
</nav>
<div class="container" >
    
{% block content %}
{% endblock %}	

</div>
<!-- Footer -->
<footer class="page-footer font-small teal pt-4">

    <!-- Footer Text -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase font-weight-bold">Footer text 1</h5>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae harum esse fugiat. Itaque, culpa?</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-6 mb-md-0 mb-3">

          <!-- Content -->
          <h5 class="text-uppercase font-weight-bold">Footer text 2</h5>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Optio deserunt fuga perferendis modi earum commodi aperiam temporibus quod nulla nesciunt aliquid debitis ullam omnis quos ipsam, aspernatur id excepturi hic.</p>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Text -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="https://mdbootstrap.com/bootstrap-tutorial/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
  </body>
</html>

templates/angelapp/create_quotes.html
{% extends "angelapp/base.html"%}
{% load widget_tweaks %}
{% block body_block %}


<h2 align='center'>Create New Quotes</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
  {% endfor %}

  {% for field in form.visible_fields %}
  
  <div class="form-group row">
    <label class="col-sm-4 col-form-label">
    {{ field.label_tag }}
    </label>
<div class="col-sm-6">
    {% render_field field class="form-control" rows=1 %}
</div>
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
  {% endfor %}
<div align='center'>
  <button  type="submit" class="btn btn-primary">Submit</button>
</div>
</form>

{% endblock %}

templates/angelapp/homepage.html
{% extends "quoteApp/base.html"%}
{% load staticfiles %}
{% block body_block %}
    <div style="text-align: center;">
      <p></p>
      <p></p>
  <H1>CHOOSE THE ROLE YOU WANT TO JOIN</H1>
  <p></p>
  <p></p>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h2 class="display-4">WISH TO BE A ANGEL</h2>
          <p>Click the button now!</p>
          <button type="button" class="btn btn-primary btn-lg col-lg-6" style="align-content: center;">ANGEL</button>
        </div>
      </div>
      <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h2 class="display-4">WISH TO BE A FREE SPIRIT</h2>
            <p>Click the button now!</p>
           <button type="button" class="btn btn-primary btn-lg col-lg-6">FREE SPIRIT</button>
          </div>
        </div>
      </div>
</div>
  </div>
</div>
{% endblock %}

templates/angelapp/list_seekers_page.html
{% extends "angelapp/base.html"%}
{% load staticfiles %}
{% block body_block %}
   <div class="container" >
  <div class="row">
  <div class="col-xs-6 col-md-2" >
    <div class="navy">
      <div class="content" background-color= "lightblue">

      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-10" background-color="#FFFFFF;">
    <div class="light">
      <div class="content">
        <p></p>
        <h1 id="quotetitle" align="center">List of Seekers</h1>
        <p></p>
        <p></p>
        {% for field in angeltable_list %}
        <div class="list-group">
            <a href="{{ field.id }}" class="list-group-item list-group-item-action">
              <p>{{ field.firstname}} {{field.lastName}}</p>
            </a>
        </div>
        {% endfor %}
        
    </div>
  </div>
</div>

</div>
{% endblock %}

templates/angelapp/quotes_list.html
{% extends "angelapp/base.html"%}
{% load staticfiles %}
{% block body_block %}
   <div class="container" >
  <div class="row">
  <div class="col-xs-6 col-md-2" >
    <div class="navy">
      <div class="content" background-color= "lightblue">

      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-10" background-color="#FFFFFF;">
    <div class="light">
      <div class="content">
        <p></p>
        <h1 id="quotetitle" align="center">List of Quotes</h1>
        <p></p>
        <p></p>
        {% for field in quotes_list %}
        <div class="list-group">
            <a href="{{ field.id }}" class="list-group-item list-group-item-action">
              <p>{{ field.quote }}</p>
            </a>
        </div>
        {% endfor %}
        
    </div>
  </div>
</div>

</div>
{% endblock %}

templates/angelapp/seekers_details.html
{% extends "angelapp/base.html"%}
{% load staticfiles %}
{% block body_block %}


<h1 align="middle"> Details of {{ details.firstname }} </h1>
{% if details.profilePic %}
<img  class="center" href="{{ details.profilePic }}" alt="" width="200" height="250">
{% endif %}
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row">Name: </th>
      <td>{{ details.firstname }} {{ details.lastName }}</td>
    </tr>
    <tr>
      <th scope="row">User Name: </th>
      <td>{{ details.username}}</td>
    </tr>
    <tr>
      <th scope="row">Gender: </th>
      <td>{{ details.gender }}</td>
    </tr>
    <tr>
      <th scope="row">Email: </th>
      <td>{{ details.email }}</td>
    </tr>
    <tr>
      <th scope="row">Description: </th>
      <td>{{ details.description }}</td>
    </tr>
    
  </tbody>
</table>
{%  if details.flag  %}
    <button type="button" class="btn btn-primary" disabled>Chat Enabled</button>
{%  else  %}
    <a href="send/{{details.deviceToken}}/{{details.firebase_id}}/"/><button type="button" class="btn btn-primary" >Chat disabled</button></a>
{%  endif  %}
{% endblock %}

templates/base.html
<!-- templates/base.html -->
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Angel APP{% endblock %}</title>

</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/termsandconditions.html
<html>
<meta content='width=device-width, initial-scale=1' name='viewport'/>
<title>Terms and conditions applied</title>
<body>
<h2>Consent form</h2>
<p>This is a consent requesting you to participate in a questionnaire that is originally devised and conducted by _________ team. The purpose of this test is to understand distress level and emotional vulnerability that an individual possess and to able to help them in best possible way.
The questionnaire is a multiple choice, subjective and a detailed questionnaire. The client or an individual taking this questionnaire is requested to answer the following accordingly with an approximate time of 15mins. This is a voluntary process and the individual is free to participate and withdraw if they feel the need for it.
Your identity will be kept confidential and your information will be assigned a code number that is unique to this application. If severe level of distress is found in an individual, the concerned guardian will be informed and further references will be made accordingly.
The responses to the questionnaire could be used for further research purposes while maintaining individual’s anonymity.
Please indicate that you have understood the nature and purpose of this test
Have you given your consent to participate in this test?</p>

<h2>Terms and conditions applied</h2>
<p>If the case is severe and if the case requires thorough attention, we may refer to a specialised professional and also the guardian will be informed whose emergency contact details are provided.
The information can be assessed only by the team and all data will be kept locked in a secure file.
When the data have been analysed for research purposes, the findings will be presented only in summary form and your name and other identity related details will not be disclosed in any report.
The participation in this test is completely voluntary. If you choose not to participate in this test, this will have no effect on the services or benefits you are currently receiving through the application. 
The participant may withdraw from the test at any time without consequences. No services will be deactivated if you choose not to finish the test. 
Risks involved in participation
Certain statements in the questionnaire may act as emotional triggers. Some may feel discomfort while answering a few questions. 
Benefits of participating
It helps the participant to gauge one’s own mental health status. A personal report will be generated according to the responses provided.</p>
</body>
</html>